require: rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - "spec/account_spec.rb"
    - "account.rb"

RSpec/MessageChain:
  Enabled: false

RSpec/NestedGroups:
  Max: 10

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 15

RSpec/MessageSpies:
  EnforcedStyle: receive

Style/Documentation:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/SubjectStub:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false
